# Generated by Django 4.2.7 on 2024-08-17 16:39

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_options_post_excerpt_post_updated_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='post',
            name='youtube_video_url',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
